-- Thermal heat → clip pipeline extensions

ALTER TABLE streamers ADD COLUMN IF NOT EXISTS game VARCHAR(255) DEFAULT '';
ALTER TABLE streamers ADD COLUMN IF NOT EXISTS current_msg_per_min INT DEFAULT 0;
ALTER TABLE streamers ADD COLUMN IF NOT EXISTS profile_image_url TEXT;
ALTER TABLE streamers ADD COLUMN IF NOT EXISTS vod_fallback_url TEXT;

ALTER TABLE heat_spikes ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE heat_spikes ADD COLUMN IF NOT EXISTS game VARCHAR(255);
ALTER TABLE heat_spikes ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE heat_spikes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE clips ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE clips ADD COLUMN IF NOT EXISTS duration_sec INT;
ALTER TABLE clips ADD COLUMN IF NOT EXISTS game VARCHAR(255);
ALTER TABLE clips ADD COLUMN IF NOT EXISTS streamer_username VARCHAR(255);
ALTER TABLE clips ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;
ALTER TABLE clips ADD COLUMN IF NOT EXISTS media_url TEXT;
ALTER TABLE clips ADD COLUMN IF NOT EXISTS tier VARCHAR(50) DEFAULT 'gateway';

CREATE INDEX IF NOT EXISTS idx_streamers_is_live ON streamers(is_live);
CREATE INDEX IF NOT EXISTS idx_heat_spikes_created_at ON heat_spikes(created_at DESC);
